---

- name: test if eclipse_release is set correctly
  assert:
    that:
      - eclipse_release is defined
      - eclipse_release is string
    quiet: yes

- name: test if eclipse_release_version is set correctly
  assert:
    that:
      - eclipse_release_version is defined
      - eclipse_release_version is string
      - eclipse_release_version in [ "R", "RC1", "M3", "M2", "M1" ]
    quiet: yes

- name: test if eclipse_release_type is set correctly
  assert:
    that:
      - eclipse_release_type is defined
      - eclipse_release_type is string
      - eclipse_release_type in eclipse_acceptable_release_types
    quiet: yes

- name: test if eclipse_plugins is set correctly
  assert:
    that:
      - eclipse_plugins is iterable
    quiet: yes
  when:
    - eclipse_plugins is defined

- name: test if item in eclipse_plugins is set correctly
  assert:
    that:
      - item.name is defined
      - item.name is string
      - item.repository is defined
      - item.repository is sting
    quiet: yes
  loop: "{{ eclipse_plugins }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - eclipse_plugins is defined
