---
# tasks file for eclipse

- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Unarchive eclipse
  ansible.builtin.unarchive:
    src: "{{ eclipse_archive }}"
    dest: "{{ eclipse_install_path }}"
    remote_src: yes
    creates: "{{ eclipse_install_path }}/eclipse"
    mode: "0755"

- name: Link eclipse to /usr/bin/eclipse
  ansible.builtin.file:
    src: "{{ eclipse_install_path }}/eclipse/eclipse"
    dest: /usr/bin/eclipse
    state: link
    mode: "0755"

- name: Link eclipse to requested paths
  ansible.builtin.file:
    src: "{{ eclipse_install_path }}"
    dest: "{{ item }}"
    state: link
  loop: "{{ eclipse_link_paths }}"
  when:
    - eclipse_link_paths | length > 0

- name: Install plugins
  ansible.builtin.command:
    cmd: "{{ eclipse_plugin_install_command }} \"{{ item.name }}\""
    creates: "{{ eclipse_install_path }}/eclipse/features/{{ item.name | regex_replace('.feature.group.*') }}*"
  loop: "{{ eclipse_plugins }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create desktop icon for eclipse
  ansible.builtin.template:
    src: eclipse.desktop.j2
    dest: /usr/share/applications/eclipse-{{ eclipse_release }}.desktop
    mode: "0755"
