---
- name: converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-eclipse
      eclipse_link_paths:
        - /opt/eclipse/eclipse-06
    - role: ansible-role-eclipse
      eclipse_release: 2022-09
      eclipse_install_path: /opt/eclipse-{{ eclipse_release }}
      eclipse_link_paths:
        - /opt/eclipse/eclipse
        - /opt/eclipse/eclipse-09
    - role: ansible-role-eclipse
      eclipse_release: 2022-12
      eclipse_install_path: /opt/eclipse-{{ eclipse_release }}
      eclipse_link_paths: []
