---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: ansible-role-eclipse
    # - role: ansible-role-eclipse
    #   eclipse_release: 2022-09
    #   eclipse_install_path: /opt/eclipse-{{ eclipse_release }}
    #   eclipse_link_paths:
    #     - /opt/eclipse-09
    #     - /opt/eclipse-202209
    # - role: ansible-role-eclipse
    #   eclipse_release: 2022-12
    #   eclipse_install_path: /opt/eclipse-{{ eclipse_release }}
    #   eclipse_link_paths: []
